version: '2'
services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TIMEZONE}
    volumes:
      - ${STORAGE_PATH}/mysql:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_PORT}:3306"
  php:
    build: 
      context: ./php-fpm
      args:
        - INSTALL_MEMCACHED=${INSTALL_MEMCACHED}
        - INSTALL_PHPREDIS=${INSTALL_PHPREDIS}
        - INSTALL_MONGO=${INSTALL_MONGO}        
        - TIMEZONE=${TIMEZONE}
    container_name: php
    links:
      - mysql
      - mongo
    volumes:
      - /var/www
      - ${APP_DIR}:/var/www/app
      - ./php-fpm/supervisor/conf.d:/etc/supervisor/conf.d
      - ./php-fpm/crontabs:/var/spool/cron/crontabs

  nginx:
    build: ./nginx
    container_name: nginx
    volumes_from:
      - php
    volumes:
      - "./nginx/conf.d:/etc/nginx/conf.d"
    links:
      - php
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
      - 8088:8081

  redis:
    image: redis:4.0.0-alpine
    container_name: redis
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ${STORAGE_PATH}/redis:/data

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ${STORAGE_PATH}/mongo:/data/db